development:
  adapter: postgresql
  encoding: unicode
  database: app_development
  username: Sadiq
  password: <%= ENV['DB_PASSWORD'] %> # stored securely in environment variables
  host: 34.56.235.138
  port: 5432
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: app_production
  username: Sadiq
  password: <%= ENV['DB_PASSWORD'] %>
  host: 34.56.235.138
  port: 5432
  pool: 5
  timeout: 5000

