amazon:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-east-1
  bucket: <%= ENV['AWS_BUCKET_NAME'] %>

google:
  service: GCS
  project: ror-deployment-440909
  credentials: <%= 
Rails.root.join("/Users/apple/Downloads/ror-deployment-440909-c30e6655ca83.json") %>
  bucket: "ror-deployment-bucket"
  path: "/"

