name: GCP Compute Engine Deployment

env:
  CLOUDSDK_CORE_LOGGING_VERBOSITY: "debug"

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  deploy:
    name: Deploy to Google Compute Engine
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Decode and Set Up Google Cloud Credentials
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcloud-key.json

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: studied-flow-384916  
        service_account_key: $HOME/gcloud-key.json
        export_default_credentials: true

    - name: Configure Docker Repository Access
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Authenticate Docker with Access Token
      run: |
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev

    - name: Build Docker Image
      run: docker build -t us-central1-docker.pkg.dev/studied-flow-384916/ror-backend/ror-backend:$GITHUB_SHA .

    - name: Push Docker Image to Artifact Registry
      run: docker push us-central1-docker.pkg.dev/studied-flow-384916/ror-backend/ror-backend:$GITHUB_SHA

    - name: Deploy to Compute Engine
      run: |
       gcloud auth activate-service-account github-actions-sa@studied-flow-384916.iam.gserviceaccount.com --key-file=$HOME/gcloud-key.json
       gcloud config set account github-actions-sa@studied-flow-384916.iam.gserviceaccount.com
       gcloud compute ssh my-learning --zone=us-central1-c --tunnel-through-iap --project=studied-flow-384916 --command "
       sudo docker pull us-central1-docker.pkg.dev/studied-flow-384916/ror-backend/ror-backend:$GITHUB_SHA &&
       sudo docker stop ror-backend || true &&
       sudo docker rm ror-backend || true &&
       sudo docker run -d -p 80:3000 --name ror-backend us-central1-docker.pkg.dev/studied-flow-384916/ror-backend/ror-backend:$GITHUB_SHA
       "


