name: GCP Compute Engine Deployment

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  deploy:
    name: Deploy to Google Compute Engine
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: studied-flow-384916  
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Build Docker Image
      run: docker build -t gcr.io/studied-flow-384916/ror-backend:$GITHUB_SHA .

    - name: Push Docker Image to Google Container Registry
      run: |
        gcloud auth configure-docker
        docker push gcr.io/studied-flow-384916/ror-backend:$GITHUB_SHA

    - name: Deploy to Compute Engine
      run: |
        gcloud compute ssh my-learning --zone=us-central1-c --command "
          docker pull gcr.io/YOUR_PROJECT_ID/ror-backend:$GITHUB_SHA &&
          docker stop ror-backend || true &&
          docker rm ror-backend || true &&
          docker run -d -p 80:3000 --name ror-backend gcr.io/YOUR_PROJECT_ID/ror-backend:$GITHUB_SHA
        "
