name: GCP Compute Engine Deployment

env:
  CLOUDSDK_CORE_LOGGING_VERBOSITY: "debug"
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Google Compute Engine
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Decode and Set Up Google Cloud Credentials
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcloud-key.json

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: studied-flow-384916  
        service_account_key: $HOME/gcloud-key.json
        export_default_credentials: true

    - name: Configure Docker Authentication for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev

    - name: Build Docker Image
      run: docker build -t us-central1-docker.pkg.dev/studied-flow-384916/ror-backend/ror-backend:$GITHUB_SHA .

    - name: Push Docker Image to Artifact Registry
      run: docker push us-central1-docker.pkg.dev/studied-flow-384916/ror-backend/ror-backend:$GITHUB_SHA

    - name: Force Update Docker Config for Artifact Registry
      run: |
        mkdir -p ~/.docker
        echo '{ "credHelpers": { "us-central1-docker.pkg.dev": "gcloud" } }' > ~/.docker/config.json
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev

    - name: Deploy to Compute Engine
      run: |
        gcloud compute ssh my-learning --zone=us-central1-c --command "
          sudo docker pull us-central1-docker.pkg.dev/studied-flow-384916/ror-backend/ror-backend:$GITHUB_SHA &&
          sudo docker stop ror-backend || true &&
          sudo docker rm ror-backend || true &&
          sudo docker run -d -p 80:8080 --name ror-backend us-central1-docker.pkg.dev/studied-flow-384916/ror-backend/ror-backend:$GITHUB_SHA
        "
