name: Deploy to Cloud Run from Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t saadiqkhn/ror-backend:$GITHUB_SHA .

      - name: Push Docker Image to Docker Hub
        run: docker push saadiqkhn/ror-backend:$GITHUB_SHA

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ror-deployment-440909
          export_default_credentials: true

      - name: Configure gcloud Account
        run: |
          gcloud config set account github-actions-deployer@ror-deployment-440909.iam.gserviceaccount.com
          gcloud config set project ror-deployment-440909

      - name: Deploy to Cloud Run from Docker Hub
        run: |
          gcloud run deploy ror-backend-service \
            --image your-dockerhub-username/ror-backend:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated




